name: test_package
description: "Test Flutter Package"
version: 0.0.1

homepage: "https://google.com"

publish_to: http://localhost:4000

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
